import './globals.css'
import { Roboto } from 'next/font/google'
import Header from './Header'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['400', '700'],
 });


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
